### ISSUE TITLE
Are API endpoints going to change/break?

### ISSUE THREAD

**Issue by Rexogamer** [Discoin/rewrite#7]
Will we need to update the URL for our requests? 

also I see we left enkiel behind but that’s beside the point

**Comment by pizzafox** [comment]
The API URL and endpoints will change and break compatibility with old bots.
The new API docs will be published online once I get the server running (probably tonight).

- [x] Write documentation
- [ ] Host documentation
- [ ] Link documentation here

**Comment by pizzafox** [comment]
API documentation is now published [here](https://discoin.zws.im/docs).
